name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint Flask pytesseract Pillow PyMuPDF spacy docstring
        pip install --force git+https://github.com/pydantic/pydantic.git@464ed49b1f813103a49116476bec75a94492b338
        python -m spacy download ru_core_news_sm

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Smelly Python
      # You may pin to the exact commit or the version.
      # uses: smelly-python/smell-my-pr@ca160cd335f89d4e536f17949521b557b9d7a0df
      uses: smelly-python/smell-my-pr@v1.0.0
      with:
        # The folder containing python files for pylint.
        command: smelly-python -d src
        # Github token
        github-token: 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
          
