name: Python Application CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install --upgrade pip
        pip install -r project/requirements.txt
        pip install --force git+https://github.com/pydantic/pydantic.git@464ed49b1f813103a49116476bec75a94492b338
        python -m spacy download ru_core_news_sm
        
    - name: Lint with pylint
      run: |
        source env/bin/activate
        pip install pylint
        pylint $(git ls-files '*.py') || true

    # - name: Run tests
    #   run: |
    #     source env/bin/activate
    #     pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install --upgrade pip
        pip install -r project/requirements.txt
        pip install --force git+https://github.com/pydantic/pydantic.git@464ed49b1f813103a49116476bec75a94492b338
        python -m spacy download ru_core_news_sm

    - name: Create SSH key file
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 GitHub.pem

    - name: Deploy to Server
      run: |
        echo "Starting deployment..."
        ssh -i GitHub.pem ubuntu@18.185.91.5 'bash -s' < .github/workflows/deploy.sh

    - name: Clean up
      run: |
        rm GitHub.pem
